# Generated by Django 6.0.4 on 2026-05-03 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialinfo',
            name='handle',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='statistic',
            constraint=models.UniqueConstraint(fields=('user', 'date_time'), name='unique_user_stat_per_day'),
        ),
    ]
