# Generated by Django 6.0.4 on 2026-05-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_socialinfo_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerlocation',
            name='latitude',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sellerlocation',
            name='longitude',
            field=models.FloatField(db_index=True),
        ),
    ]
